version: '3'
services:
  conda-python3.6-tensorflow:
    build: ./conda-python3.6-tensorflow
    image: tiangolo/python-machine-learning:conda-python3.6-tensorflow
  conda-cuda9.1-python3.6-tensorflow:
    build: ./conda-cuda9.1-python3.6-tensorflow
    image: tiangolo/python-machine-learning:conda-cuda9.1-python3.6-tensorflow
